### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by gedw99** [wav/grpc-web-dart#3]
Can you add the flutter example that works with the books service.

Got an idea to try to get pub sub pushing from a golang KV store underneath the server to get the whole stack working.

Also very curious to try the web client code for book service too

**Comment by gedw99** [comment]
If you can't due to closed client.
Could you just rip out anything not for public and dump the uncompiling code into a GitHub repo 
I can then build up the demo to work with the existing server.

Ask me if anything not ok :)

**Comment by wav** [comment]
An example has been added. Have fun!
